name: upsol_loyalty
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  # Hanya gunakan satu package supabase
  supabase_flutter: ^2.12.0
  google_fonts: ^8.0.1
  intl: ^0.20.2
  image_picker: ^1.2.1
  url_launcher: ^6.3.2
  permission_handler: ^11.3.0
  # Hanya gunakan mobile_scanner, sisanya dihapus agar APK tidak bengkak
  mobile_scanner: ^5.1.0 
  # Tambahan untuk keamanan key
  flutter_dotenv: ^5.1.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - .env # Daftarkan file .env di sini